name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This will be fixed following our GitFlow process (likely as a hotfix if critical).

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system down, data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround exists)
    validations:
      required: true

  - type: dropdown
    id: branch-type
    attributes:
      label: Suggested Fix Type
      description: Based on severity, what type of branch should fix this?
      options:
        - hotfix/ (critical production issue)
        - feature/ (can wait for next release)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - OS: [e.g., macOS 14.0]
        - Browser: [e.g., Chrome 120]
        - Node version: [e.g., 20.10.0]
        - App version: [e.g., 1.0.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or console logs
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all relevant information
          required: true
        - label: I understand the GitFlow process for fixes
          required: true