name: Feature Request
description: Suggest a new feature for the project
title: "[Feature]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! This will be implemented following our GitFlow process.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clear and concise description of the feature you'd like
      placeholder: As a [user type], I want [feature] so that [benefit]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks work)
        - High (significant impact)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be considered complete?
      placeholder: |
        - [ ] User can...
        - [ ] System should...
        - [ ] Feature must...
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: Suggested Branch Name
      description: Following GitFlow conventions (feature/your-feature-name)
      placeholder: feature/user-authentication
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I understand this will follow the GitFlow process
          required: true